# asdf expects zsh to be installed
- hosts: "guibuntu"
  tasks:
    - name: Install packages
      become: yes
      apt:
        name: 
          - curl
          - tree
          - snapd
          - git
          - steam
          - wget
          - apt-transport-https
          - ca-certificates
          - gnupg
          - lsb-release
          - vim
        state: latest

    - name: Install snap packages
      become: yes
      community.general.snap:
        name:
          - vlc
          - discord 
          - spotify
          - signal-desktop

    - name: Install IntelliJ
      become: yes
      community.general.snap:
        name: intellij-idea-ultimate
        classic: yes

    - name: Download asdf
      git:
        repo: "https://github.com/asdf-vm/asdf.git"
        dest: "~/.asdf"
        update: yes
        version: v0.8.1

    - name: Looking for ZSH 
      stat: 
        path: ~/.zshrc
      register: stat_result

    - name: Check if ZSH is configured
      lineinfile: 
         path: ~/.zshrc
         line: ". $HOME/.asdf/asdf.sh"
         state: present
      check_mode: yes
      register: config_line
      failed_when: (config_line is changed) or (config_line is failed)

    - name: Configure asdf for zsh
      shell: echo ". $HOME/.asdf/asdf.sh" >> ~/.zshrc
      when: stat_result.stat.exists and config_line.stat.exists


    - name: add element apt key
      become: yes
      apt_key:
        url: https://packages.element.io/debian/element-io-archive-keyring.gpg
        state: present

    - name: add element apt repository
      become: yes
      apt_repository: 
        repo: deb https://packages.element.io/debian/ default main
        state: present 
        filename: element-io 
        update_cache: yes

    - name: install element
      become: yes
      apt:
        name: element-desktop

    - name: add docker apt key
      become: yes
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: add docker apt repository
      become: yes
      apt_repository: 
        repo: "deb https://download.docker.com/linux/ubuntu focal stable"
        state: present 
        filename: docker
        update_cache: yes

    - name: install docker
      become: yes
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
