- hosts: "guibuntu"
  tasks:

    - name: install prerequisites
      become: true
      apt:
        name: apt-transport-https
        state: present

    - name: add apt key
      become: true
      apt_key:
        url: https://download.sublimetext.com/sublimehq-pub.gpg
        state: present

    - name: Add apt repository
      become: true
      apt_repository: 
        repo: deb https://download.sublimetext.com/ apt/stable/
        state: present 
        filename: sublime-text 
        update_cache: yes

    - name: install sublime
      become: true
      apt:
        name: sublime-text
        state: present

    - name: Install package control
      get_url:
        url: https://packagecontrol.io/Package%20Control.sublime-package
        dest: "~/.config/sublime-text/Packages/User/Package Control.sublime-package"

    - name: Install packages and config
      copy:
        src: "sublime/{{ item }}"
        dest: "~/.config/sublime-text/Packages/User/{{ item }}"
      with_items:
        - Anaconda.sublime-settings
        - Package Control.sublime-settings
        - Preferences.sublime-settings
        - Python.sublime-settings
